// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxfvhkmfgtmhoylawzor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZnZoa21mZ3RtaG95bGF3em9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NTU2ODgsImV4cCI6MjA3NjIzMTY4OH0.e_I3O5Le3fO4Uo1WwAZn3ztrhZusukZcQCL4SitcDcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});